### PR TITLE
add new ast-sync operation, make ast a global executable

### PR DESCRIPTION
**Pull request by CuBeRJAN**
ast is now shared for all snapshots, this makes keeping it updated much easier
there's also a new ast-sync operation that automatically updates ast

### CODE REVIEW

**Review by i2 — COMMENTED** [review]
Great! This is going to be a critical and welcome change for future of our code-base.
My initial feedback: It would be nice to give user an option to turn "calling home" on and off. Some users might prefer an all-offline ast and they'll update when they want.

**Comment by CuBeRJAN** [comment]
the ast-sync has to be specifically run by the user, and if the user wants to update manually then they can replace the file in /.snapshots/ast/ast
I think a mention in the documentation would be good

**Comment by i2** [comment]
> the ast-sync has to be specifically run by the user, and if the user wants to update manually then they can replace the file in /.snapshots/ast/ast I think a mention of the manual update in the documentation would be good

Sounds good on both accounts.
I'm good with that so long as user has the option!

**Comment by CuBeRJAN** [comment]
So I think we can merge now? Unless you want to do more testing of course.

**Comment by i2** [comment]
> So I think we can merge now? Unless you want to do more testing of course.

I'm doing a few more tests. So far so good.

**Comment by i2** [comment]
I'd like to make sure there are no negative side-effects of ignoring ast-lock when ast-syncing.

**Comment by CuBeRJAN** [comment]
The behaviour of lock in ast wasn't changed, I only added a comment to clear up the fact that it's not used currently.

**Pull request merged**
