### PR TITLE
add fix for duplicate fstab entry

### PR DESCRIPTION
**Pull request by CuBeRJAN**
this is an automatic fix for the duplicate fstab entry issue
https://github.com/astos/astos/commit/817675de2a060d8cdf242da1c7a9b7af1ab5fede

### CODE REVIEW

**Comment by i2** [comment]
This only affects users who have installed before ()[https://github.com/astos/astos/commit/817675de2a060d8cdf242da1c7a9b7af1ab5fede], correct?

**Comment by CuBeRJAN** [comment]
that is correct, in case the user installed after that commit this bit of code doesn't do anything

**Comment by i2** [comment]
To keep codebase minimal, I would say let's not add this. I'd say just send a message to affected users in the discord channel and a little snippet in README.md. This snippet can be removed after a while when we are user people have moved on to recent version.

**Comment by CuBeRJAN** [comment]
Sounds alright!

**Pull request closed without merging**
